// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Currencies");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("tbody", undefined, React.createElement("tr", undefined, React.createElement("td", undefined, "1"), React.createElement("td", undefined, "Bitcoin"), React.createElement("td", undefined, "$139,936,962,941"), React.createElement("td", undefined, "$8,302.61"), React.createElement("td", undefined, "$8,378,290,000"), React.createElement("td", undefined, "16,854,575 BTC"), React.createElement("td", undefined, "-2.03%")));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
