// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React                    = require("react");
var ReasonReact              = require("reason-react/src/ReasonReact.js");
var Currencies$ReactTemplate = require("./currencies.bs.js");

var component = ReasonReact.statelessComponent("Table");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("table", undefined, React.createElement("thead", undefined, React.createElement("tr", undefined, React.createElement("th", undefined, "#"), React.createElement("th", undefined, "Name"), React.createElement("th", undefined, "Market Cap"), React.createElement("th", undefined, "Price"), React.createElement("th", undefined, "Volume (24h)"), React.createElement("th", undefined, "Circulating Supply"), React.createElement("th", undefined, "Change (24h)"))), ReasonReact.element(/* None */0, /* None */0, Currencies$ReactTemplate.make(/* array */[])));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
